export default {
    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    LOGOUT: 'USER_LOGOUT',

    ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
    FETCH_TODOS_SUCCESS: 'GET_TODO_SUCCESS',
    UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS'
};
